apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
spec:
  provider: aws
  objectStorage:
    bucket: {{ index .Values.configuration.backupStorageLocation 0 "bucket" }}
  config:
    region: {{ index .Values.configuration.backupStorageLocation 0 "config" "region" }}
