apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: velero-ingress
spec:
  rules:
    - host: velero.cloudmasa.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: velero
                port:
                  number: 80
