apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: default
spec:
  provider: aws
  config:
    region: {{ index .Values.configuration.volumeSnapshotLocation 0 "config" "region" }}
